server/src/main/java/org/gluu/oxtrust/action/ConfigureLogViewerAction.java
/*
 * oxTrust is available under the MIT License (2008). See http://opensource.org/licenses/MIT for full text.
 *
 * Copyright (c) 2014, Gluu
 */

package org.gluu.oxtrust.action;

import java.io.IOException;
import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.ConversationScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Inject;
import javax.inject.Named;

import org.gluu.jsf2.message.FacesMessages;
import org.gluu.jsf2.service.ConversationService;
import org.gluu.oxtrust.ldap.service.ApplianceService;
import org.gluu.oxtrust.ldap.service.JsonConfigurationService;
import org.gluu.oxtrust.model.GluuAppliance;
import org.gluu.oxtrust.model.LogViewerConfig;
import org.gluu.oxtrust.model.SimpleCustomPropertiesListModel;
import org.gluu.oxtrust.service.logger.LoggerService;
import org.gluu.oxtrust.util.OxTrustConstants;
import org.slf4j.Logger;
import org.xdi.model.SimpleCustomProperty;
import org.xdi.oxauth.model.configuration.AppConfiguration;
import org.xdi.service.JsonService;
import org.xdi.service.security.Secure;
import org.xdi.util.StringHelper;

/**
 * Action class for configuring log viewer
 *
 * @author Yuriy Movchan Date: 07/08/2013
 */
@Named("configureLogViewerAction")
@ConversationScoped
@Secure("#{permissionService.hasPermission('configuration', 'access')}")
public class ConfigureLogViewerAction implements SimpleCustomPropertiesListModel, Serializable {

	private static final long serialVersionUID = -3310460481895022468L;

	@Inject
	private Logger log;

	@Inject
	private ApplianceService applianceService;

	@Inject
	private FacesMessages facesMessages;

	@Inject
	private ConversationService conversationService;

	@Inject
	private JsonService jsonService;

	@Inject
	private LoggerService loggerService;

	@Inject
	private JsonConfigurationService jsonConfigurationService;

	private GluuAppliance appliance;

	private String oxTrustLogConfigLocation;
	private String oxAuthLogConfigLocation;

	private LogViewerConfig logViewerConfiguration;

	private boolean initialized;

	public String init() {
		if (this.logViewerConfiguration != null) {
			return OxTrustConstants.RESULT_SUCCESS;
		}

		this.appliance = applianceService.getAppliance();
		this.oxTrustLogConfigLocation = appliance.getOxLogConfigLocation();
		
		try {
			this.oxAuthLogConfigLocation = jsonConfigurationService.getOxauthAppConfiguration().getExternalLoggerConfiguration();
		} catch (Exception e) {
			log.error("Failed to retrieve oxauth configuration", e);
		}

		initConfigurations();

		this.initialized = true;

		return OxTrustConstants.RESULT_SUCCESS;
	}

	private void initConfigurations() {
		this.logViewerConfiguration = prepareLogViewerConfig();
	}

	public String update() {
		if (!validateLists()) {
			facesMessages.add(FacesMessage.SEVERITY_ERROR, "Failed to update log viewer configuration");
			return OxTrustConstants.RESULT_FAILURE;
		}

		updateAppliance();
		updateOxAuthConfiguration();

    facesMessages.add(FacesMessage.SEVERITY_INFO, "Log viewer configuration updated");

		return OxTrustConstants.RESULT_SUCCESS;
	}

	private void updateAppliance() {
		GluuAppliance updateAppliance = applianceService.getAppliance();
		try {
			updateAppliance.setOxLogViewerConfig(jsonService.objectToJson(logViewerConfiguration));
			updateAppliance.setOxLogConfigLocation(oxTrustLogConfigLocation);

			applianceService.updateAppliance(updateAppliance);
			loggerService.updateLoggerConfigLocation();
		} catch (Exception ex) {
			log.error("Failed to save log viewer configuration '{}'", ex);
		}
	}

	private void updateOxAuthConfiguration() {
		try {
			AppConfiguration appConfiguration = jsonConfigurationService.getOxauthAppConfiguration();
			appConfiguration.setExternalLoggerConfiguration(oxAuthLogConfigLocation);
			jsonConfigurationService.saveOxAuthAppConfiguration(appConfiguration);
		} catch (IOException e) {
			log.error("Failed to update oxauth-config.json", e);
			facesMessages.add(FacesMessage.SEVERITY_ERROR, "Failed to update oxAuth configuration in LDAP");
		}
	}

	private boolean validateLists() {
		boolean result = true;

		return result;
	}

	public String cancel() {
		facesMessages.add(FacesMessage.SEVERITY_INFO, "Log viewer configuration update were canceled");
		conversationService.endConversation();

		return OxTrustConstants.RESULT_SUCCESS;
	}

	private LogViewerConfig prepareLogViewerConfig() {
		LogViewerConfig logViewerConfig = null;

		String oxLogViewerConfig = appliance.getOxLogViewerConfig();
		if (StringHelper.isNotEmpty(oxLogViewerConfig)) {
			try {
				logViewerConfig = jsonService.jsonToObject(appliance.getOxLogViewerConfig(), LogViewerConfig.class);
			} catch (Exception ex) {
				log.error("Failed to load log viewer configuration '{}'", oxLogViewerConfig, ex);
			}
		}

		if (logViewerConfig == null) {
			logViewerConfig = new LogViewerConfig();
		}

		return logViewerConfig;
	}

	public boolean isInitialized() {
		return initialized;
	}

	@Override
	public void addItemToSimpleCustomProperties(List<SimpleCustomProperty> simpleCustomProperties) {
		if (simpleCustomProperties != null) {
			simpleCustomProperties.add(new SimpleCustomProperty("description", ""));
		}
	}

	@Override
	public void removeItemFromSimpleCustomProperties(List<SimpleCustomProperty> simpleCustomProperties,
			SimpleCustomProperty simpleCustomProperty) {
		if (simpleCustomProperties != null) {
			simpleCustomProperties.remove(simpleCustomProperty);
		}
	}

	public LogViewerConfig getLogViewerConfiguration() {
		return logViewerConfiguration;
	}

	public String getOxTrustLogConfigLocation() {
		return oxTrustLogConfigLocation;
	}

	public void setOxTrustLogConfigLocation(String oxTrustLogConfigLocation) {
		this.oxTrustLogConfigLocation = oxTrustLogConfigLocation;
	}

	public String getOxAuthLogConfigLocation() {
		return oxAuthLogConfigLocation;
	}

	public void setOxAuthLogConfigLocation(String oxAuthLogConfigLocation) {
		this.oxAuthLogConfigLocation = oxAuthLogConfigLocation;
	}
}

server/src/main/java/org/gluu/oxtrust/action/ViewLogFileAction.java
/*
 * oxTrust is available under the MIT License (2008). See http://opensource.org/licenses/MIT for full text.
 *
 * Copyright (c) 2014, Gluu
 */

package org.gluu.oxtrust.action;

import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.io.Serializable;
import java.nio.charset.Charset;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.enterprise.context.ConversationScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.commons.io.FilenameUtils;
import org.apache.commons.io.filefilter.AndFileFilter;
import org.apache.commons.io.filefilter.FileFileFilter;
import org.apache.commons.io.filefilter.WildcardFileFilter;
import org.gluu.jsf2.message.FacesMessages;
import org.gluu.oxtrust.ldap.service.ApplianceService;
import org.gluu.oxtrust.model.GluuAppliance;
import org.gluu.oxtrust.model.LogViewerConfig;
import org.gluu.oxtrust.util.OxTrustConstants;
import org.slf4j.Logger;
import org.xdi.model.SimpleCustomProperty;
import org.xdi.service.JsonService;
import org.xdi.service.security.Secure;
import org.xdi.util.StringHelper;
import org.xdi.util.io.ReverseLineReader;

/**
 * Action class for configuring log viewer
 * 
 * @author Yuriy Movchan Date: 07/08/2013
 */
@ConversationScoped
@Named
@Secure("#{permissionService.hasPermission('log', 'access')}")
public class ViewLogFileAction implements Serializable {

	private static final long serialVersionUID = -3310340481895022468L;

	@Inject
	private Logger log;
	
	@Inject
	private ApplianceService applianceService;

	@Inject
	private FacesMessages facesMessages;

	@Inject
	private JsonService jsonService;

	private GluuAppliance appliance;

	private LogViewerConfig logViewerConfiguration;
	private Map<Integer, String> logFiles;

	private boolean initialized;

	private int activeLogFileIndex;
	
	private String currentLogFileName="";

	private int displayLastLinesCount;

	public String init() {
		if (this.logViewerConfiguration != null) {
			return OxTrustConstants.RESULT_SUCCESS;
		}

		this.appliance = applianceService.getAppliance();

		initConfigurations();
		
		this.activeLogFileIndex = -1;
		
		this.displayLastLinesCount = 400;
		this.initialized = true;

		return OxTrustConstants.RESULT_SUCCESS;
	}

	private void initConfigurations() {
		this.logViewerConfiguration = prepareLogViewerConfig();

		this.logFiles = prepareLogFiles();
	}

	private LogViewerConfig prepareLogViewerConfig() {
		LogViewerConfig logViewerConfig = null;

		String oxLogViewerConfig = appliance.getOxLogViewerConfig();
		if (StringHelper.isNotEmpty(oxLogViewerConfig)) {
			try {
				logViewerConfig = jsonService.jsonToObject(appliance.getOxLogViewerConfig(), LogViewerConfig.class);
			} catch (Exception ex) {
				log.error("Failed to load log viewer configuration '{}'", oxLogViewerConfig, ex);
			}
		}

		if (logViewerConfig == null) {
			logViewerConfig = new LogViewerConfig();
		}

		return logViewerConfig;
	}

	private Map<Integer, String> prepareLogFiles() {
		Map<Integer, String> logFiles = new HashMap<Integer, String>();

		int fileIndex = 0;
		for (SimpleCustomProperty logTemplate : this.logViewerConfiguration.getLogTemplates()) {
			String logTemplatePattern = logTemplate.getValue2();
			if (StringHelper.isEmpty(logTemplatePattern)) {
				continue;
			}

			String logTemplatePath = FilenameUtils.getFullPath(logTemplatePattern);
			String logTemplateFile = FilenameUtils.getName(logTemplatePattern);

			File logTemplateBaseDir = new File(logTemplatePath);

			FileFilter fileFilter = new AndFileFilter(FileFileFilter.FILE, new WildcardFileFilter(logTemplateFile));
			File[] files = logTemplateBaseDir.listFiles(fileFilter);
			if (files == null) {
				continue;
			}

			for (int i = 0; i < files.length; i++) {
				logFiles.put(fileIndex++, files[i].getPath());
			}
		}

		return logFiles;
	}

	public boolean isInitialized() {
		return initialized;
	}

	public LogViewerConfig getLogViewerConfiguration() {
		return logViewerConfiguration;
	}

	public Map<Integer, String> getLogFiles() {
		return logFiles;
	}

	public String getTailOfLogFile() {
		if (this.activeLogFileIndex == -1) {
			return "No content available";
		}
		setCurrentLogFileName(this.logFiles.get(activeLogFileIndex));
		File activeLogFile = new File(this.logFiles.get(activeLogFileIndex));
		ReverseLineReader reverseLineReader = new ReverseLineReader(activeLogFile, Charset.defaultCharset().name());
		try {
			List<String> logFileLastLines = reverseLineReader.readLastLines(this.displayLastLinesCount);
			
			StringBuilder sb = new StringBuilder();
			for (String logFileLastLine : logFileLastLines) {
				sb.append(logFileLastLine);
				sb.append('\n');
			}
			
			return sb.toString();
		} catch (IOException ex) {
			log.error("Failed to read log file '{}'", this.logFiles.get(activeLogFileIndex), ex);
			String result = String.format("Failed to read log file '%s'", this.logFiles.get(activeLogFileIndex));
			
			return result;
		} finally {
			try {
				reverseLineReader.close();
			} catch (IOException ex) {
				log.error("Failed to destory ReverseLineReader", ex);
			}
		}
	}

	public int getActiveLogFileIndex() {
		return activeLogFileIndex;
	}

	public void setActiveLogFileIndex(int activeLogFileIndex) {
		this.activeLogFileIndex = activeLogFileIndex;
		setCurrentLogFileName(this.logFiles.get(this.activeLogFileIndex));
	}


	public int getDisplayLastLinesCount() {
		return displayLastLinesCount;
	}

	public void setDisplayLastLinesCount(int displayLinesCount) {
		this.displayLastLinesCount = displayLinesCount;
	}

	public String getCurrentLogFileName() {
		return currentLogFileName;
	}

	public void setCurrentLogFileName(String currentLogFileName) {
		this.currentLogFileName = currentLogFileName;
	}
	
	

}

server/src/main/webapp/logviewer/configureLogViewer.xhtml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:ox="http://xmlns.jcp.org/jsf/composite/ox"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/WEB-INF/incl/layout/newtemplate.xhtml">
    <f:metadata>
        <f:viewAction action="#{conversationService.initConversation}" />
        <f:viewAction action="#{configureLogViewerAction.init}" onPostback="false"/>
    </f:metadata>

    <ui:define name="body">
        <section class="content-header">
            <h1 style="color: #333;">
                #{msg['logViewer.configuration']}
                <small>
                    <i class="fa fa-caret-right"
                       style="color: #333 !important;"/> #{msg['logViewer.configureLogViewer']}</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    <a href="#{request.contextPath}/home">
                        <i class="fa fa-home"/>
                    </a>
                </li>
                <li class="organization/configuration">
                    <a href="#{request.contextPath}/logviewer/configure">#{msg['logViewer.configureLogViewer']}</a>
                </li>
            </ol>
        </section>
        <section class="content">

            <div id="formArea">
                <h:form id="logViewerForm">
                    <f:validateBean>
                    <div class="row">

                        <div class="col-xs-12">
                            <div class="box box-primary">
                                <div class="box-header">
                                </div>

                                <div style="display: inline-block; width: 75% !important;">

                                    <h:panelGroup>
                                        <div class="row" style="padding:5px;margin-bottom: 5px;margin-left:0px">
                                            <ox:decorate 
                                            	forId="oxTrustLogConfigLocation" label="oxTrust External log4j location">
                                            <h:inputText id="oxTrustLogConfigLocation" class="col-md-4 form-control oxTrustLogConfigLocation"
                                                         style="margin-right:5px;margin-bottom:10px;width:42%;float:left;"
                                                         value="#{configureLogViewerAction.oxTrustLogConfigLocation}"></h:inputText>
                                        </ox:decorate>
                                        </div>
                                        <div class="row" style="padding:5px;margin-bottom: 5px;margin-left:0px">
                                        <ox:decorate 
                                            	forId="oxTrustLogConfigLocation" label="oxAuth External log4j location">
                                            
                                            <h:inputText id="oxAuthLogConfigLocation" class="col-md-4 form-control oxAuthLogConfigLocation"
                                                         style="margin-right:5px;margin-bottom:10px;width:42%;float:left;"
                                                         value="#{configureLogViewerAction.oxAuthLogConfigLocation}"></h:inputText>
                                        </ox:decorate>
                                        </div>
                                        <ox:simpleCustomPropertiesList label="#{msg['logViewer.allowedLogTemplates']}"
                                                                       labelAdd="#{msg['logViewer.logTemplate']}"
                                                                       leftClass="col-sm-2"
                                                                       rightClass="col-sm-10"
                                                                       properties="#{configureLogViewerAction.logViewerConfiguration.logTemplates}"
                                                                       propertiesAction="#{configureLogViewerAction}"/>
                                    </h:panelGroup>


                                </div>
                                <div class="box-footer">

                                    <div id="updateButtons">
                                        <h:commandButton action="#{configureLogViewerAction.update}"
                                                         styleClass="btn btn-primary addLogButtonClass"
                                                         value="#{msg['logViewer.update']}"/>
                                        <h:commandButton action="#{configureLogViewerAction.cancel}" immediate="true"
                                                         style="margin-left:5px" styleClass="btn btn-primary"
                                                         value="#{msg['logViewer.cancel']}"/>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    </f:validateBean>
                </h:form>
            </div>
        </section>
    </ui:define>

</ui:composition>

server/src/main/webapp/logviewer/viewLogFile.xhtml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ox="http://xmlns.jcp.org/jsf/composite/ox"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	template="/WEB-INF/incl/layout/newtemplate.xhtml">
	<f:metadata>
		<f:viewAction action="#{conversationService.initConversation}" />
		<f:viewAction action="#{viewLogFileAction.init}" onPostback="false" />
	</f:metadata>

	<ui:define name="head">
		<style type="text/css">
.overflowed {
	overflow-x: scroll;
}
</style>

	</ui:define>

	<ui:define name="body">
		<section class="content-header">
			<h1 style="color: #333;">
				#{msg['logViewer.configuration']} <small> <i
					class="fa fa-caret-right" style="color: #333 !important;" />
					#{msg['logViewer.viewLogFile']}
				</small>
			</h1>
			<ol class="breadcrumb">
				<li><a href="#{request.contextPath}/home"> <i
						class="fa fa-home" />
				</a></li>
				<li class="organization/configuration"><a
					href="#{request.contextPath}/logviewer/view">#{msg['logViewer.viewLogFile']}</a>
				</li>
			</ol>
		</section>
		<section class="content">
			<div id="formArea">
				<h:form id="logViewForm">
					<f:validateBean>
						<!-- Workaround which required by manual tab panel. TODO: Remove after upgrade to SEAM 2.3.1 -->
						<input name="cid" type="hidden" value="#{conversation.id}" />


						<div class="row">
							<div class="col-xs-12">
								<div class="nav-tabs-custom" style="margin-bottom: 0px;">
									<ul class="nav nav-tabs" id="logViewFormtab">
										<li class="active"><a data-toggle="tab"
											href="#logged-files">#{msg['logViewer.allowedLogFiles']}</a>
										</li>
										<li><a data-toggle="tab" href="#config">#{msg['logViewer.configuration']}</a>
										</li>
										<li><a data-toggle="tab" href="#tail">#{msg['logViewer.tailOfLogFile']}</a>
										</li>

									</ul>
									<div class="tab-content">
										<!-- System Configuration -->
										<div class="tab-pane active" id="logged-files">

											<div style="display: inline-block; width: 75% !important;">

												<rich:panel bodyClass="noPadding" header="Allowed log files"
													width="100%">
													<h:panelGroup border="0" cellpadding="0" cellspacing="0"
														columns="1" width="100%">
														<a4j:repeat
															value="#{viewLogFileAction.logFiles.entrySet().toArray()}"
															var="_logFile">
															<div>
																<a4j:commandLink
																	action="#{viewLogFileAction.setActiveLogFileIndex(_logFile.key)}"
																	execute="@form" limitRender="true"
																	onclick="$('.nav-tabs a[href=\'#tail\']').tab('show');"
																	render="viewLogPanelId" value="#{_logFile.value}" />
															</div>
															<br />
														</a4j:repeat>
													</h:panelGroup>
												</rich:panel>
											</div>
										</div>
										<div class="tab-pane" id="config">

											<div style="display: inline-block; width: 75% !important;">

												<h:panelGroup>
													<ox:decorate
														label="#{msg['logViewer.displayLastLinesCount']}">
														<h:inputText required="true" styleClass="form-control"
															value="#{viewLogFileAction.displayLastLinesCount}" />
													</ox:decorate>
												</h:panelGroup>
											</div>
										</div>
										<div class="tab-pane" id="tail">

											<div style="display: inline-block; width: 75% !important;">

												<h:panelGroup id="viewLogPanelId" layout="block"
													styleClass="overflowed">
													<h1>#{viewLogFileAction.getCurrentLogFileName()}</h1>
													<pre>
                            <h:outputText
															value="#{viewLogFileAction.getTailOfLogFile()}" />
                        </pre>
													<h1>#{viewLogFileAction.getCurrentLogFileName()}</h1>
												</h:panelGroup>
											</div>
										</div>
									</div>
								</div>


								<script>
									$('#logViewFormtab a').click(function(e) {
										e.preventDefault();
										$(this).tab('show');
									});

									// store the currently selected tab in the local storage
									$("ul.nav-tabs > li > a")
											.on(
													"shown.bs.tab",
													function(e) {
														var id = $(e.target)
																.attr("href")
																.substr(1);
														window.localStorage
																.setItem(
																		'logViewFormtab',
																		id);
														var storeValue = window.localStorage
																.getItem('logViewFormtab');
													});

									// on load of the page: switch to the currently selected tab
									$(document)
											.ready(
													function() {
														var value = window.localStorage
																.getItem('logViewFormtab');
														if (value) {
															var activeTab = "#";
															activeTab = activeTab
																	.concat(value);
															$(
																	'#logViewFormtab a[href="'
																			+ activeTab
																			+ '"]')
																	.tab('show');
														}
													});
								</script>

							</div>
						</div>
					</f:validateBean>
				</h:form>
			</div>
		</section>
	</ui:define>
</ui:composition>